<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

    public function run()
    {
            Country::insert([
                ['name_ru' => 'Россия', 'name_en' => 'Russia', 'flag' => 'ru'],
                ['name_ru' => 'США', 'name_en' => 'United States', 'flag' => 'us'],
                ['name_ru' => 'Канада', 'name_en' => 'Canada', 'flag' => 'ca'],
                ['name_ru' => 'Китай', 'name_en' => 'China', 'flag' => 'cn'],
                ['name_ru' => 'Япония', 'name_en' => 'Japan', 'flag' => 'jp'],
                ['name_ru' => 'Германия', 'name_en' => 'Germany', 'flag' => 'de'],
                ['name_ru' => 'Франция', 'name_en' => 'France', 'flag' => 'fr'],
                ['name_ru' => 'Великобритания', 'name_en' => 'United Kingdom', 'flag' => 'gb'],
                ['name_ru' => 'Индия', 'name_en' => 'India', 'flag' => 'in'],
                ['name_ru' => 'Бразилия', 'name_en' => 'Brazil', 'flag' => 'br'],
                ['name_ru' => 'Италия', 'name_en' => 'Italy', 'flag' => 'it'],
                ['name_ru' => 'Австралия', 'name_en' => 'Australia', 'flag' => 'au'],
                ['name_ru' => 'Испания', 'name_en' => 'Spain', 'flag' => 'es'],
                ['name_ru' => 'Мексика', 'name_en' => 'Mexico', 'flag' => 'mx'],
                ['name_ru' => 'Южная Корея', 'name_en' => 'South Korea', 'flag' => 'kr'],
                ['name_ru' => 'Аргентина', 'name_en' => 'Argentina', 'flag' => 'ar'],
                ['name_ru' => 'Чили', 'name_en' => 'Chile', 'flag' => 'cl'],
                ['name_ru' => 'Колумбия', 'name_en' => 'Colombia', 'flag' => 'co'],
                ['name_ru' => 'Эфиопия', 'name_en' => 'Ethiopia', 'flag' => 'et'],
                ['name_ru' => 'Египет', 'name_en' => 'Egypt', 'flag' => 'eg'],
                ['name_ru' => 'Финляндия', 'name_en' => 'Finland', 'flag' => 'fi'],
                ['name_ru' => 'Греция', 'name_en' => 'Greece', 'flag' => 'gr'],
                ['name_ru' => 'Иран', 'name_en' => 'Iran', 'flag' => 'ir'],
                ['name_ru' => 'Ирак', 'name_en' => 'Iraq', 'flag' => 'iq'],
                ['name_ru' => 'Израиль', 'name_en' => 'Israel', 'flag' => 'il'],
                ['name_ru' => 'Саудовская Аравия', 'name_en' => 'Saudi Arabia', 'flag' => 'sa'],
                ['name_ru' => 'ЮАР', 'name_en' => 'South Africa', 'flag' => 'za'],
                ['name_ru' => 'Норвегия', 'name_en' => 'Norway', 'flag' => 'no'],
                ['name_ru' => 'Швеция', 'name_en' => 'Sweden', 'flag' => 'se'],
                ['name_ru' => 'Нидерланды', 'name_en' => 'Netherlands', 'flag' => 'nl'],
                ['name_ru' => 'Бельгия', 'name_en' => 'Belgium', 'flag' => 'be'],
                ['name_ru' => 'Швейцария', 'name_en' => 'Switzerland', 'flag' => 'ch'],
                ['name_ru' => 'Австрия', 'name_en' => 'Austria', 'flag' => 'at'],
                ['name_ru' => 'Дания', 'name_en' => 'Denmark', 'flag' => 'dk'],
                ['name_ru' => 'Ирландия', 'name_en' => 'Ireland', 'flag' => 'ie'],
                ['name_ru' => 'Португалия', 'name_en' => 'Portugal', 'flag' => 'pt'],
                ['name_ru' => 'Польша', 'name_en' => 'Poland', 'flag' => 'pl'],
                ['name_ru' => 'Чехия', 'name_en' => 'Czech Republic', 'flag' => 'cz'],
                ['name_ru' => 'Словакия', 'name_en' => 'Slovakia', 'flag' => 'sk'],
                ['name_ru' => 'Венгрия', 'name_en' => 'Hungary', 'flag' => 'hu'],
                ['name_ru' => 'Румыния', 'name_en' => 'Romania', 'flag' => 'ro'],
                ['name_ru' => 'Болгария', 'name_en' => 'Bulgaria', 'flag' => 'bg'],
                ['name_ru' => 'Хорватия', 'name_en' => 'Croatia', 'flag' => 'hr'],
                ['name_ru' => 'Словения', 'name_en' => 'Slovenia', 'flag' => 'si'],
                ['name_ru' => 'Сербия', 'name_en' => 'Serbia', 'flag' => 'rs'],
                ['name_ru' => 'Черногория', 'name_en' => 'Montenegro', 'flag' => 'me'],
                ['name_ru' => 'Босния и Герцеговина', 'name_en' => 'Bosnia and Herzegovina', 'flag' => 'ba'],
                ['name_ru' => 'Северная Македония', 'name_en' => 'North Macedonia', 'flag' => 'mk'],
                ['name_ru' => 'Албания', 'name_en' => 'Albania', 'flag' => 'al'],
                ['name_ru' => 'Грузия', 'name_en' => 'Georgia', 'flag' => 'ge'],
                ['name_ru' => 'Армения', 'name_en' => 'Armenia', 'flag' => 'am'],
                ['name_ru' => 'Азербайджан', 'name_en' => 'Azerbaijan', 'flag' => 'az'],
                ['name_ru' => 'Казахстан', 'name_en' => 'Kazakhstan', 'flag' => 'kz'],
                ['name_ru' => 'Узбекистан', 'name_en' => 'Uzbekistan', 'flag' => 'uz'],
                ['name_ru' => 'Туркмения', 'name_en' => 'Turkmenistan', 'flag' => 'tm'],
                ['name_ru' => 'Киргизия', 'name_en' => 'Kyrgyzstan', 'flag' => 'kg'],
                ['name_ru' => 'Таджикистан', 'name_en' => 'Tajikistan', 'flag' => 'tj'],
                ['name_ru' => 'Украина', 'name_en' => 'Ukraine', 'flag' => 'ua'],
                ['name_ru' => 'Беларусь', 'name_en' => 'Belarus', 'flag' => 'by'],
                ['name_ru' => 'Латвия', 'name_en' => 'Latvia', 'flag' => 'lv'],
                ['name_ru' => 'Литва', 'name_en' => 'Lithuania', 'flag' => 'lt'],
                ['name_ru' => 'Эстония', 'name_en' => 'Estonia', 'flag' => 'ee'],
                ['name_ru' => 'Молдова', 'name_en' => 'Moldova', 'flag' => 'md'],
                ['name_ru' => 'Исландия', 'name_en' => 'Iceland', 'flag' => 'is'],
                ['name_ru' => 'Гренландия', 'name_en' => 'Greenland', 'flag' => 'gl'],
                ['name_ru' => 'Монако', 'name_en' => 'Monaco', 'flag' => 'mc'],
                ['name_ru' => 'Лихтенштейн', 'name_en' => 'Liechtenstein', 'flag' => 'li'],
                ['name_ru' => 'Люксембург', 'name_en' => 'Luxembourg', 'flag' => 'lu'],
                ['name_ru' => 'Мальта', 'name_en' => 'Malta', 'flag' => 'mt'],
                ['name_ru' => 'Кипр', 'name_en' => 'Cyprus', 'flag' => 'cy'],
                ['name_ru' => 'Сингапур', 'name_en' => 'Singapore', 'flag' => 'sg'],
                ['name_ru' => 'Малайзия', 'name_en' => 'Malaysia', 'flag' => 'my'],
                ['name_ru' => 'Таиланд', 'name_en' => 'Thailand', 'flag' => 'th'],
                ['name_ru' => 'Вьетнам', 'name_en' => 'Vietnam', 'flag' => 'vn'],
                ['name_ru' => 'Индонезия', 'name_en' => 'Indonesia', 'flag' => 'id'],
                ['name_ru' => 'Филиппины', 'name_en' => 'Philippines', 'flag' => 'ph'],
                ['name_ru' => 'Мьянма', 'name_en' => 'Myanmar', 'flag' => 'mm'],
                ['name_ru' => 'Камбоджа', 'name_en' => 'Cambodia', 'flag' => 'kh'],
                ['name_ru' => 'Лаос', 'name_en' => 'Laos', 'flag' => 'la'],
                ['name_ru' => 'Бангладеш', 'name_en' => 'Bangladesh', 'flag' => 'bd'],
                ['name_ru' => 'Шри-Ланка', 'name_en' => 'Sri Lanka', 'flag' => 'lk'],
                ['name_ru' => 'Пакистан', 'name_en' => 'Pakistan', 'flag' => 'pk'],
                ['name_ru' => 'Афганистан', 'name_en' => 'Afghanistan', 'flag' => 'af'],
                ['name_ru' => 'Непал', 'name_en' => 'Nepal', 'flag' => 'np'],
                ['name_ru' => 'Бутан', 'name_en' => 'Bhutan', 'flag' => 'bt'],
                ['name_ru' => 'Мальдивы', 'name_en' => 'Maldives', 'flag' => 'mv'],
                ['name_ru' => 'Турция', 'name_en' => 'Turkey', 'flag' => 'tr'],
                ['name_ru' => 'Ливан', 'name_en' => 'Lebanon', 'flag' => 'lb'],
                ['name_ru' => 'Иордания', 'name_en' => 'Jordan', 'flag' => 'jo'],
                ['name_ru' => 'Сирия', 'name_en' => 'Syria', 'flag' => 'sy'],
                ['name_ru' => 'Ирак', 'name_en' => 'Iraq', 'flag' => 'iq'],
                ['name_ru' => 'Кувейт', 'name_en' => 'Kuwait', 'flag' => 'kw'],
                ['name_ru' => 'Бахрейн', 'name_en' => 'Bahrain', 'flag' => 'bh'],
                ['name_ru' => 'Катар', 'name_en' => 'Qatar', 'flag' => 'qa'],
                ['name_ru' => 'ОАЭ', 'name_en' => 'United Arab Emirates', 'flag' => 'ae'],
                ['name_ru' => 'Оман', 'name_en' => 'Oman', 'flag' => 'om'],
                ['name_ru' => 'Йемен', 'name_en' => 'Yemen', 'flag' => 'ye'],
                ['name_ru' => 'Палестина', 'name_en' => 'Palestine', 'flag' => 'ps'],
                ['name_ru' => 'Судан', 'name_en' => 'Sudan', 'flag' => 'sd'],
                ['name_ru' => 'Южный Судан', 'name_en' => 'South Sudan', 'flag' => 'ss'],
                ['name_ru' => 'Эритрея', 'name_en' => 'Eritrea', 'flag' => 'er'],
                ['name_ru' => 'Джибути', 'name_en' => 'Djibouti', 'flag' => 'dj'],
                ['name_ru' => 'Сомали', 'name_en' => 'Somalia', 'flag' => 'so'],
                ['name_ru' => 'Кения', 'name_en' => 'Kenya', 'flag' => 'ke'],
                ['name_ru' => 'Уганда', 'name_en' => 'Uganda', 'flag' => 'ug'],
                ['name_ru' => 'Руанда', 'name_en' => 'Rwanda', 'flag' => 'rw'],
                ['name_ru' => 'Бурунди', 'name_en' => 'Burundi', 'flag' => 'bi'],
                ['name_ru' => 'Танзания', 'name_en' => 'Tanzania', 'flag' => 'tz'],
                ['name_ru' => 'Сейшелы', 'name_en' => 'Seychelles', 'flag' => 'sc'],
                ['name_ru' => 'Коморы', 'name_en' => 'Comoros', 'flag' => 'km'],
                ['name_ru' => 'Маврикий', 'name_en' => 'Mauritius', 'flag' => 'mu'],
                ['name_ru' => 'Мадагаскар', 'name_en' => 'Madagascar', 'flag' => 'mg'],
                ['name_ru' => 'Мозамбик', 'name_en' => 'Mozambique', 'flag' => 'mz'],
                ['name_ru' => 'Замбия', 'name_en' => 'Zambia', 'flag' => 'zm'],
                ['name_ru' => 'Зимбабве', 'name_en' => 'Zimbabwe', 'flag' => 'zw'],
                ['name_ru' => 'Ботсвана', 'name_en' => 'Botswana', 'flag' => 'bw'],
                ['name_ru' => 'Намибия', 'name_en' => 'Namibia', 'flag' => 'na'],
                ['name_ru' => 'Ангола', 'name_en' => 'Angola', 'flag' => 'ao'],
                ['name_ru' => 'ДР Конго', 'name_en' => 'Democratic Republic of the Congo', 'flag' => 'cd'],
                ['name_ru' => 'Республика Конго', 'name_en' => 'Republic of the Congo', 'flag' => 'cg'],
                ['name_ru' => 'Габон', 'name_en' => 'Gabon', 'flag' => 'ga'],
                ['name_ru' => 'Экваториальная Гвинея', 'name_en' => 'Equatorial Guinea', 'flag' => 'gq']
            ]);
    }
}
