<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

    public function run()
    {
        Country::insert([
            ['name_ru' =>     'Россия', 'name_en' =>  'Russia'],
            ['name_ru' =>     'США', 'name_en' =>  'United States'],
            ['name_ru' =>     'Канада', 'name_en' =>  'Canada'],
            ['name_ru' =>     'Китай', 'name_en' =>  'China'],
            ['name_ru' =>     'Япония', 'name_en' =>  'Japan'],
            ['name_ru' =>     'Германия', 'name_en' =>  'Germany'],
            ['name_ru' =>     'Франция', 'name_en' =>  'France'],
            ['name_ru' =>     'Великобритания', 'name_en' =>  'United Kingdom'],
            ['name_ru' =>     'Индия', 'name_en' =>  'India'],
            ['name_ru' =>     'Бразилия', 'name_en' =>  'Brazil'],
            ['name_ru' =>     'Италия', 'name_en' =>  'Italy'],
            ['name_ru' =>     'Австралия', 'name_en' =>  'Australia'],
            ['name_ru' =>     'Испания', 'name_en' =>  'Spain'],
            ['name_ru' =>     'Мексика', 'name_en' =>  'Mexico'],
            ['name_ru' =>     'Южная Корея', 'name_en' =>  'South Korea'],
            ['name_ru' =>     'Аргентина', 'name_en' =>  'Argentina'],
            ['name_ru' =>     'Чили', 'name_en' =>  'Chile'],
            ['name_ru' =>     'Колумбия', 'name_en' =>  'Colombia'],
            ['name_ru' =>     'Эфиопия', 'name_en' =>  'Ethiopia'],
            ['name_ru' =>     'Египет', 'name_en' =>  'Egypt'],
            ['name_ru' =>     'Финляндия', 'name_en' =>  'Finland'],
            ['name_ru' =>     'Греция', 'name_en' =>  'Greece'],
            ['name_ru' =>     'Иран', 'name_en' =>  'Iran'],
            ['name_ru' =>     'Ирак', 'name_en' =>  'Iraq'],
            ['name_ru' =>     'Израиль', 'name_en' =>  'Israel'],
            ['name_ru' =>     'Саудовская Аравия', 'name_en' =>  'Saudi Arabia'],
            ['name_ru' =>     'ЮАР', 'name_en' =>  'South Africa'],
            ['name_ru' =>     'Норвегия', 'name_en' =>  'Norway'],
            ['name_ru' =>     'Швеция', 'name_en' =>  'Sweden'],
            ['name_ru' =>     'Нидерланды', 'name_en' =>  'Netherlands'],
            ['name_ru' =>     'Бельгия', 'name_en' =>  'Belgium'],
            ['name_ru' =>     'Швейцария', 'name_en' =>  'Switzerland'],
            ['name_ru' =>     'Австрия', 'name_en' =>  'Austria'],
            ['name_ru' =>     'Дания', 'name_en' =>  'Denmark'],
            ['name_ru' =>     'Ирландия', 'name_en' =>  'Ireland'],
            ['name_ru' =>     'Португалия', 'name_en' =>  'Portugal'],
            ['name_ru' =>     'Польша', 'name_en' =>  'Poland'],
            ['name_ru' =>     'Чехия', 'name_en' =>  'Czech Republic'],
            ['name_ru' =>     'Словакия', 'name_en' =>  'Slovakia'],
            ['name_ru' =>     'Венгрия', 'name_en' =>  'Hungary'],
            ['name_ru' =>     'Румыния', 'name_en' =>  'Romania'],
            ['name_ru' =>     'Болгария', 'name_en' =>  'Bulgaria'],
            ['name_ru' =>     'Хорватия', 'name_en' =>  'Croatia'],
            ['name_ru' =>     'Словения', 'name_en' =>  'Slovenia'],
            ['name_ru' =>     'Сербия', 'name_en' =>  'Serbia'],
            ['name_ru' =>     'Черногория', 'name_en' =>  'Montenegro'],
            ['name_ru' =>     'Босния и Герцеговина', 'name_en' =>  'Bosnia and Herzegovina'],
            ['name_ru' =>     'Северная Македония', 'name_en' =>  'North Macedonia'],
            ['name_ru' =>     'Албания', 'name_en' =>  'Albania'],
            ['name_ru' =>     'Грузия', 'name_en' =>  'Georgia'],
            ['name_ru' =>     'Армения', 'name_en' =>  'Armenia'],
            ['name_ru' =>     'Азербайджан', 'name_en' =>  'Azerbaijan'],
            ['name_ru' =>     'Казахстан', 'name_en' =>  'Kazakhstan'],
            ['name_ru' =>     'Узбекистан', 'name_en' =>  'Uzbekistan'],
            ['name_ru' =>     'Туркмения', 'name_en' =>  'Turkmenistan'],
            ['name_ru' =>     'Киргизия', 'name_en' =>  'Kyrgyzstan'],
            ['name_ru' =>     'Таджикистан', 'name_en' =>  'Tajikistan'],
            ['name_ru' =>     'Украина', 'name_en' =>  'Ukraine'],
            ['name_ru' =>     'Беларусь', 'name_en' =>  'Belarus'],
            ['name_ru' =>     'Латвия', 'name_en' =>  'Latvia'],
            ['name_ru' =>     'Литва', 'name_en' =>  'Lithuania'],
            ['name_ru' =>     'Эстония', 'name_en' =>  'Estonia'],
            ['name_ru' =>     'Молдова', 'name_en' =>  'Moldova'],
            ['name_ru' =>     'Исландия', 'name_en' =>  'Iceland'],
            ['name_ru' =>     'Гренландия', 'name_en' =>  'Greenland'],
            ['name_ru' =>     'Монако', 'name_en' =>  'Monaco'],
            ['name_ru' =>     'Лихтенштейн', 'name_en' =>  'Liechtenstein'],
            ['name_ru' =>     'Люксембург', 'name_en' =>  'Luxembourg'],
            ['name_ru' =>     'Мальта', 'name_en' =>  'Malta'],
            ['name_ru' =>     'Кипр', 'name_en' =>  'Cyprus'],
            ['name_ru' =>     'Сингапур', 'name_en' =>  'Singapore'],
            ['name_ru' =>     'Малайзия', 'name_en' =>  'Malaysia'],
            ['name_ru' =>     'Таиланд', 'name_en' =>  'Thailand'],
            ['name_ru' =>     'Вьетнам', 'name_en' =>  'Vietnam'],
            ['name_ru' =>     'Индонезия', 'name_en' =>  'Indonesia'],
            ['name_ru' =>     'Филиппины', 'name_en' =>  'Philippines'],
            ['name_ru' =>     'Мьянма', 'name_en' =>  'Myanmar'],
            ['name_ru' =>     'Камбоджа', 'name_en' =>  'Cambodia'],
            ['name_ru' =>     'Лаос', 'name_en' =>  'Laos'],
            ['name_ru' =>     'Бангладеш', 'name_en' =>  'Bangladesh'],
            ['name_ru' =>     'Шри-Ланка', 'name_en' =>  'Sri Lanka'],
            ['name_ru' =>     'Пакистан', 'name_en' =>  'Pakistan'],
            ['name_ru' =>     'Афганистан', 'name_en' =>  'Afghanistan'],
            ['name_ru' =>     'Непал', 'name_en' =>  'Nepal'],
            ['name_ru' =>     'Бутан', 'name_en' =>  'Bhutan'],
            ['name_ru' =>     'Мальдивы', 'name_en' =>  'Maldives'],
            ['name_ru' =>     'Турция', 'name_en' =>  'Turkey'],
            ['name_ru' =>     'Ливан', 'name_en' =>  'Lebanon'],
            ['name_ru' =>     'Иордания', 'name_en' =>  'Jordan'],
            ['name_ru' =>     'Сирия', 'name_en' =>  'Syria'],
            ['name_ru' =>     'Ирак', 'name_en' =>  'Iraq'],
            ['name_ru' =>     'Кувейт', 'name_en' =>  'Kuwait'],
            ['name_ru' =>     'Бахрейн', 'name_en' =>  'Bahrain'],
            ['name_ru' =>     'Катар', 'name_en' =>  'Qatar'],
            ['name_ru' =>     'ОАЭ', 'name_en' =>  'United Arab Emirates'],
            ['name_ru' =>     'Оман', 'name_en' =>  'Oman'],
            ['name_ru' =>     'Йемен', 'name_en' =>  'Yemen'],
            ['name_ru' =>     'Палестина', 'name_en' =>  'Palestine'],
            ['name_ru' =>     'Судан', 'name_en' =>  'Sudan'],
            ['name_ru' =>     'Южный Судан', 'name_en' =>  'South Sudan'],
            ['name_ru' =>     'Эритрея', 'name_en' =>  'Eritrea'],
            ['name_ru' =>     'Джибути', 'name_en' =>  'Djibouti'],
            ['name_ru' =>     'Сомали', 'name_en' =>  'Somalia'],
            ['name_ru' =>     'Кения', 'name_en' =>  'Kenya'],
            ['name_ru' =>     'Уганда', 'name_en' =>  'Uganda'],
            ['name_ru' =>     'Руанда', 'name_en' =>  'Rwanda'],
            ['name_ru' =>     'Бурунди', 'name_en' =>  'Burundi'],
            ['name_ru' =>     'Танзания', 'name_en' =>  'Tanzania'],
            ['name_ru' =>     'Сейшелы', 'name_en' =>  'Seychelles'],
            ['name_ru' =>     'Коморы', 'name_en' =>  'Comoros'],
            ['name_ru' =>     'Маврикий', 'name_en' =>  'Mauritius'],
            ['name_ru' =>     'Мадагаскар', 'name_en' =>  'Madagascar'],
            ['name_ru' =>     'Мозамбик', 'name_en' =>  'Mozambique'],
            ['name_ru' =>     'Замбия', 'name_en' =>  'Zambia'],
            ['name_ru' =>     'Зимбабве', 'name_en' =>  'Zimbabwe'],
            ['name_ru' =>     'Ботсвана', 'name_en' =>  'Botswana'],
            ['name_ru' =>     'Намибия', 'name_en' =>  'Namibia'],
            ['name_ru' =>     'Ангола', 'name_en' =>  'Angola'],
            ['name_ru' =>     'ДР Конго', 'name_en' =>  'Democratic Republic of the Congo'],
            ['name_ru' =>     'Конго', 'name_en' =>  'Republic of the Congo'],
            ['name_ru' =>     'Габон', 'name_en' =>  'Gabon'],
            ['name_ru' =>     'Экваториальная Гвинея', 'name_en' =>  'Equatorial Guinea'],
        ]);
    }
}
